### ISSUE TITLE
unlimited results!!!

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [notroaloch/artworks-finder#1]

**Comment by KENPOKASMMA1982** [comment]
> woow what amazing job!but please could you make it increase unlimited results and search also by date and year?it would be great!!! There is a parameter called offset, which is not mentioned in API documentation.

https://itunes.apple.com/search?term=a&offset=25&limit=25

**Comment by KENPOKASMMA1982** [comment]
hello!please could you increase unlimited results with scroll infinity or with load more? There is a parameter called offset, which is not mentioned in API documentation.

https://itunes.apple.com/search?term=a&offset=25&limit=25

**Comment by notroaloch** [comment]
@KENPOKASMMA1982 Thanks for your suggestion!
